services:
  - type: web
    name: template-sharing-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: template_sharing_db
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: BASE_URL
        value: https://template-sharing-backend.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
